config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :new, :show, :create] do 
    resources :bookmarks, only: [:new, :create] 
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<h1>Ok</h1>

app/views/bookmarks/new.html.erb
<h1>Ok</h1>
<div class="class container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Submit new bookmark", class: "btn btn-info" %>
  <% end %>
</div>
<%= link_to "Back to all lists", lists_path  %>

app/views/bookmarks/show.html.erb
<h1>Ok</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list) %>
    </li>
  <% end %>
</ul>

<%= link_to "Add new list", new_list_path %>

app/views/lists/new.html.erb
<h1>Add a new list</h1>
<div class="class container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.association :movies %>
    <%= f.association :bookmarks %>
    <%= f.submit "Submit new list", class: "btn btn-info" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<h1> <%= @list.name %> </h1>
<%= link_to "Back to all lists", lists_path  %>
<%= link_to "Add bookmark", new_list_bookmark_path(@list) %>
<%= link_to "See bookmark", list_bookmarks_path(@list) %>